### ISSUE TITLE
How to Run this Project

### ISSUE THREAD

**Issue by CiaShangLin** [manuelseeger/sc2-ai-coach#1]
Hey there! I'm really excited about this cool project and I'd love to give it a try. Could you provide some instructions on how to install it?

I'm an Android developer, so I'm not very familiar with Python. Do I need to purchase ChatGPT 4 to run this project? I've tried setting up a virtual environment using venv and the environment-cp310.yml file, but I encountered some errors along the way.

I'm submitting this issue through ChatGPT's translation feature. Any help would be greatly appreciated!

I am a GM Master Protoss "Nzs"

**Comment by manuelseeger** [comment]
Hey there! Please understand that his is a hobby programming project and not meant to be ready to use. I did add some documentation on how to run it: 
https://github.com/manuelseeger/sc2-ai-coach?tab=readme-ov-file#how-to-run

But you will need Python programming experience and it will take some trial and error to get this running.

**Comment by CiaShangLin** [comment]
Thank you for your response, I will give it a try.

**Comment by manuelseeger** [comment]
I have updated the project with a minimal (text-only) setup which doesn't need advanced hardware and should be much easier to get running. 

https://github.com/manuelseeger/sc2-ai-coach?tab=readme-ov-file#minimal-setup
